
##### ---- Functions ---- #####


## Functions used, organized by script that uses them ##


# Find the estimates for mu_hat (the ratio estimator), Y_hat (numerator, thing we're interested in), and 
#    X_Hat (denominator, density of things like total trees of a species). See Equation 6 and related.
mean.q.fcn <- function(dat_tot, resp, spp.sel1) {     #dat_tot = data frame of species total for a quantile (denominator). resp = response data frame (numerator) for quantile.
  
  Zt <- Yv <- R <- 0 #  rep(0,length(sppname))    # Mean difference in response for a given species: Zt = Mean value for total trees, 
  #Yv = mean value for/of trees of interest (mean # that died), R = ratio of the two.
  #for (i in 1:length(sppname)) {                         # i indexes species
  col.spp <- grep(paste0("nd.", spp.sel1),  colnames(dat_tot))
  col.name <- paste0("nd.", spp.sel1)
  
  Zt_i <- Yv_i <-  rep(0, strat.num)  # Weighted values for each strata
  for (h in 1:strat.num) {                  # h indexes strata
    n_h <- length(dat_tot$STRATUM[dat_tot$STRATUM == strat2$STRATUM[h]] )    # Number of plots in stratum h with species of interest
    Zt_i[h] <- strat2$W_h[h] * sum(get(col.name, dat_tot)[dat_tot$STRATUM == strat2$STRATUM[h]]) / n_h     
    Yv_i[h] <- strat2$W_h[h] * sum(get(col.name, resp)[resp$STRATUM == strat2$STRATUM[h]]) / n_h     
  }
  Zt <- sum(Zt_i) 
  Yv <- sum(Yv_i) 
  R <- Yv / Zt
  
  means <- list(Zt = Zt, Yv = Yv, R = R)
  return(means)
}

# Helper functions for ratio.SE.fcn: 
# Function that finds variance or covariance for individual strata in the function ratio.SE.fcn
varcov.fcn <- function(xy.sum, xsum, ysum, nnh) {(1/(nnh * (nnh - 1))) * (xy.sum - (1/nnh) * xsum * ysum)} # Equations 10 and 11

# Function that finds the overall weighted variance and covariance in the function ratio.SE.fcn
wt.varcov.fcn <- function(vc, nnh, nn) {(1/nn) * (sum(strat2$W_h * nnh * vc) + sum((1 - strat2$W_h) * (nnh/nn) * vc))} # Equations 8 and 9


# Find the standard error of the variance for a species' quartile
ratio.SE.fcn <- function(d.all_z, d.ado_y, meandat)	{   # ii = column for response variable, meandat = list generated by actmean function
  
  col.spp <- which(colnames(d.all_z) == paste0("nd.", spp.sel)) # ID the column for the species in question
  
  Zt <- meandat$Zt   # Output from mean.q.fcn
  mu <- meandat$R    # Output from mean.q.fcn
  
  
  # for (i in 1:length(sppname))	{
  Zh <- Yh <- nn_h <- Zu2h <- Yu2h <- ZYh <- rep(0, length(strat2$STRATUM))  # Weighted values for each strata
  for(h in 1:length(strat2$STRATUM)){ 
    # Pieces for calculating stratum-level variances.
    # Number of plots in each stratum:
    nn_h[h] <- length(d.ado_y$STRATUM[d.ado_y$STRATUM == strat2$STRATUM[h]])
    # For each stratum h for each species, first calculate the Z and Y values.
    Zh[h] <- sum(d.all_z[d.all_z$STRATUM == strat2$STRATUM[h], col.spp])
    Yh[h] <- sum(d.ado_y[d.ado_y$STRATUM == strat2$STRATUM[h], col.spp])
    # Square values for Z and Y (for Step 6, 7, and 8)
    Zu2h[h] <- sum(d.all_z[d.all_z$STRATUM == strat2$STRATUM[h], col.spp] ^ 2)
    Yu2h[h] <- sum(d.ado_y[d.ado_y$STRATUM == strat2$STRATUM[h], col.spp] ^ 2)
    # ZY cross-products between first or second visits(for steps 9, 10)
    ZYh[h] <- sum(d.all_z[d.all_z$STRATUM == strat2$STRATUM[h], col.spp] * d.ado_y[d.ado_y$STRATUM == strat2$STRATUM[h], col.spp])
    
  }
  
  (7121 - 592*(0.00571^2))/(592 * (592 - 1))
  (Zu2h[18] - (1/nn_h[18])*Zh[18]^2)/(nn_h[18] * (nn_h[18] - 1))

  varcov.fcn <- function(xy.sum, xsum, ysum, nnh) {(1/(nnh * (nnh - 1))) * (xy.sum - (1/nnh) * xsum * ysum)} # Equations 10 and 11
  
  nn <- dim(d.all_z)[1]   # nn = N = total plots including ones not sampled
  
  # Weighed variances (Step 8 of algorithm sheet)
  varZ <- varcov.fcn(Zu2h, Zh, Zh, nn_h)
  varY <- varcov.fcn(Yu2h, Yh, Yh, nn_h)
  covZY <- varcov.fcn(ZYh, Zh, Yh, nn_h)
  
  w.varZ <- wt.varcov.fcn(varZ, nn_h, nn)
  w.varY <- wt.varcov.fcn(varY, nn_h, nn)
  
  # Covariances for visit-pair estimator (Step 11)
  w.covZY <- wt.varcov.fcn(covZY, nn_h, nn)
  
  # Variance of ratios (Step 12)
  
  varR <- (1/Zt^2) * (w.varY + mu^2 * w.varZ - 2 * mu * w.covZY)  ## Clean up for production.  Can verify using monte carlo
  
  varR
}



